#!/bin/sh

# You will need gcc-fortran, cpio, freeglut, glu

export PROGSDIR=$HOME/CalculiX-2.14
export PATH=$PROGSDIR/bin:$PATH
export LD_LIBRARY_PATH=$PROGSDIR/lib:$LD_LIBRARY_PATH
export INCLUDE=$PROGSDIR/include:$INCLUDE
export LDFLAGS="-L$PROGSDIR/lib"
export CPPFLAGS="-I$PROGSDIR/include"
export MY_LIB=$PROGSDIR/lib
export MY_INCLUDE=$PROGSDIR/include
export HOME_BUILD=$PWD

mkdir -p $PROGSDIR
mkdir -p $PROGSDIR/bin
mkdir -p $PROGSDIR/lib
mkdir -p $PROGSDIR/doc
mkdir -p $PROGSDIR/include


### Spooles as solver for CCX
#-----------------------------
echo 'Building Spooles'
cd SPOOLES.2.2
#make lib > ../spooles_make.txt 2> ../spooles_error.txt
make lib
cp spooles.a $PROGSDIR/lib
mkdir $PROGSDIR/include/spooles
find . -name '*.h' | cpio -updm $PROGSDIR/include/spooles
cd MT/src
#make > ../../../spoolesMT_make.txt 2> ../../../spoolesMT_error.txt
make
cp spoolesMT.a $PROGSDIR/lib
cd ..
cp spoolesMT.h $PROGSDIR/include/spooles/MT
cd ../..


### Install ARPACK to support CalculiX
#--------------------------------------
echo 'Building ARPACK'
cd ARPACK
#make lib > ../ARPACK_make.txt 2> ../ARPACK_error.txt
make lib
cp libarpack_linux.a $PROGSDIR/lib
cd ..


### CGX from CalculiX
#---------------------
echo 'Installing CGX'
cd CalculiX/cgx_2.14/src
#make > ../../../cgx_make.txt 2> ../../../cgx_error.txt
make
cp cgx $PROGSDIR/bin
cd ../../..
cp cgx_2.14.pdf $PROGSDIR/doc/
rm cgx_2.14.pdf


### CCX 2.14 with pardiso and spooles
#-------------------------------------
echo 'Installing CCX 2.14'
cd CalculiX/ccx_2.14/src
#make > ../../../ccx_make.txt 2> ../../../ccx_error.txt
make
cp ccx_2.14 $PROGSDIR/bin
cp LOGBOOK $PROGSDIR/doc
cd ../../..
cp ccx_2.14.pdf $PROGSDIR/doc
rm ccx_2.14.pdf
